/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guateroad;

/**
 *
 * @author Jeany
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setSize(530,560);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bttLogin = new javax.swing.JButton();
        bttRegistrar = new javax.swing.JButton();
        OpConductor = new javax.swing.JToggleButton();
        OpAdmin = new javax.swing.JToggleButton();
        OpUser = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        jLabel1.setText("Guateroad");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 80, 220, 100);

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        getContentPane().add(txtPass);
        txtPass.setBounds(200, 230, 180, 30);

        txtUsuario.setToolTipText("Usuario");
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(200, 170, 180, 30);

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel3.setText("Contraseña");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 230, 90, 30);

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel4.setText("Usuario");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 180, 70, 20);

        bttLogin.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bttLogin.setText("Login");
        bttLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLoginActionPerformed(evt);
            }
        });
        getContentPane().add(bttLogin);
        bttLogin.setBounds(280, 330, 100, 40);

        bttRegistrar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bttRegistrar.setText("Registrar");
        bttRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(bttRegistrar);
        bttRegistrar.setBounds(140, 330, 100, 40);

        OpConductor.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        OpConductor.setText("Conductor");
        OpConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpConductorActionPerformed(evt);
            }
        });
        getContentPane().add(OpConductor);
        OpConductor.setBounds(190, 280, 110, 25);

        OpAdmin.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        OpAdmin.setText("Administrador");
        getContentPane().add(OpAdmin);
        OpAdmin.setBounds(290, 280, 130, 25);

        OpUser.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        OpUser.setText("Usuario");
        getContentPane().add(OpUser);
        OpUser.setBounds(103, 280, 90, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guateroad/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 510, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void bttLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLoginActionPerformed
        String Usuario, password; 
        Usuario = txtUsuario.getText();
        Guateroad.contraseña = txtPass.getText();
        password = Guateroad.fn.EncriptarSHA256(txtPass.getText());;
        if ((txtUsuario.getText().equals("andree_avalos")) && (txtPass.getText().equals("admin")) && (OpAdmin.isSelected())) //Evaluando si es el administrador 
        {
            Admin administrador = new Admin();
            administrador.setVisible(true);
            dispose();
        }
        
        if(OpUser.isSelected())
        {
            Guateroad.id = Guateroad.ArbolUsuario.ObtenerId(Usuario, password);
            if (Guateroad.ArbolUsuario.Buscar(Guateroad.id))
            {
                Usuario user = new Usuario();
                user.setVisible(true);
                dispose();
                //Abrir la interfaz del usuario normal 
            }
            
        }
        
        if(OpConductor.isSelected())
        {
            Guateroad.id = Guateroad.ArbolConductor.ObtenerId(Usuario, password);
            if (Guateroad.ArbolConductor.Buscar(Guateroad.id))
            {
                Conductor cdtor = new Conductor();
                cdtor.setVisible(true);
                dispose();
            }
        }
    }//GEN-LAST:event_bttLoginActionPerformed

    private void OpConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpConductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpConductorActionPerformed

    private void bttRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRegistrarActionPerformed
        Registrar Nuevo = new Registrar();
        Nuevo.setVisible(true);
    }//GEN-LAST:event_bttRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton OpAdmin;
    private javax.swing.JToggleButton OpConductor;
    private javax.swing.JToggleButton OpUser;
    private javax.swing.JButton bttLogin;
    private javax.swing.JButton bttRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
