/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guateroad;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeany
 */
public class Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();        
        this.setSize(750,510);
        txtCorreo.setVisible(false);
        txtName.setVisible(false);
        txtPass.setVisible(false);
        txtTel.setVisible(false);
        txtUser.setVisible(false);
        lblNombre.setText(Guateroad.ArbolUsuario.UsuarioP(Guateroad.id));
        lblName.setText(Guateroad.ArbolUsuario.NombreP(Guateroad.id));
        lblCorreo.setText(Guateroad.ArbolUsuario.CorreoP(Guateroad.id));
        lblPass.setText(Guateroad.ArbolUsuario.PassP(Guateroad.id));
        lblTel.setText(Guateroad.ArbolUsuario.TelefonoP(Guateroad.id));
        lblUser.setText(Guateroad.ArbolUsuario.UsuarioP(Guateroad.id));
        
        for(int i = 0; i < Guateroad.HashT.cantTotal(); i++)
        {
            if (Guateroad.HashT.Categoria(i).equals("vacio"))
            {
                System.out.println(Guateroad.HashT.Categoria(i));
            }
            else 
            {
                System.out.println(Guateroad.HashT.Nombre(i));
                Opciones.addItem(Guateroad.HashT.Nombre(i));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        bttModificar = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        bttGuardar = new javax.swing.JButton();
        bttCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Opciones = new javax.swing.JComboBox<>();
        bttRuta = new javax.swing.JButton();
        bttInicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblNombre.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblNombre);
        lblNombre.setBounds(550, 20, 150, 20);

        lblName.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblName);
        lblName.setBounds(40, 60, 230, 30);

        lblUser.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblUser);
        lblUser.setBounds(40, 110, 230, 30);

        lblPass.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lblPass.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblPass);
        lblPass.setBounds(40, 160, 400, 30);

        lblCorreo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblCorreo);
        lblCorreo.setBounds(40, 210, 230, 30);

        lblTel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        lblTel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblTel);
        lblTel.setBounds(40, 260, 230, 30);

        bttModificar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bttModificar.setText("Modificar");
        bttModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttModificarActionPerformed(evt);
            }
        });
        getContentPane().add(bttModificar);
        bttModificar.setBounds(30, 350, 110, 25);

        txtName.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        getContentPane().add(txtName);
        txtName.setBounds(40, 60, 230, 30);

        txtTel.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        getContentPane().add(txtTel);
        txtTel.setBounds(40, 260, 230, 30);

        txtUser.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        getContentPane().add(txtUser);
        txtUser.setBounds(40, 110, 230, 30);

        txtPass.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        getContentPane().add(txtPass);
        txtPass.setBounds(40, 160, 230, 30);

        txtCorreo.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        getContentPane().add(txtCorreo);
        txtCorreo.setBounds(40, 210, 230, 30);

        bttGuardar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bttGuardar.setText("Guardar");
        bttGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(bttGuardar);
        bttGuardar.setBounds(160, 350, 110, 25);

        bttCerrar.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bttCerrar.setText("Cerrar");
        bttCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(bttCerrar);
        bttCerrar.setBounds(100, 390, 110, 25);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Viajes");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 80, 100, 25);

        Opciones.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionesActionPerformed(evt);
            }
        });
        getContentPane().add(Opciones);
        Opciones.setBounds(480, 120, 170, 30);

        bttRuta.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bttRuta.setText("Cargar Ruta");
        bttRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRutaActionPerformed(evt);
            }
        });
        getContentPane().add(bttRuta);
        bttRuta.setBounds(500, 190, 130, 25);

        bttInicio.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        bttInicio.setText("Inicio");
        bttInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttInicioActionPerformed(evt);
            }
        });
        getContentPane().add(bttInicio);
        bttInicio.setBounds(610, 400, 110, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guateroad/AzulRosa.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 450);

        jMenu2.setText("Perfil");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Lugares");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void bttModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttModificarActionPerformed
        txtCorreo.setVisible(true);
        txtName.setVisible(true);
        txtPass.setVisible(true);
        txtTel.setVisible(true);
        txtUser.setVisible(true);
        txtName.setText(Guateroad.ArbolUsuario.NombreP(Guateroad.id));
        txtCorreo.setText(Guateroad.ArbolUsuario.CorreoP(Guateroad.id));
        txtPass.setText(Guateroad.contraseña);
        txtTel.setText(Guateroad.ArbolUsuario.TelefonoP(Guateroad.id));
        txtUser.setText(Guateroad.ArbolUsuario.UsuarioP(Guateroad.id));
    }//GEN-LAST:event_bttModificarActionPerformed

    private void bttGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttGuardarActionPerformed
        Guateroad.contraseña = txtPass.getText();
        Guateroad.ArbolUsuario.setCorreo(Guateroad.id, txtCorreo.getText());
        Guateroad.ArbolUsuario.setNom(Guateroad.id, txtName.getText());
        Guateroad.ArbolUsuario.setPass(Guateroad.id, txtPass.getText());
        Guateroad.ArbolUsuario.setTel(Guateroad.id, txtTel.getText());
        Guateroad.ArbolUsuario.setUs(Guateroad.id, txtUser.getText());
        txtCorreo.setVisible(false);
        txtName.setVisible(false);
        txtPass.setVisible(false);
        txtTel.setVisible(false);
        txtUser.setVisible(false);
        lblNombre.setText(Guateroad.ArbolUsuario.UsuarioP(Guateroad.id));
        lblName.setText(Guateroad.ArbolUsuario.NombreP(Guateroad.id));
        lblCorreo.setText(Guateroad.ArbolUsuario.CorreoP(Guateroad.id));
        lblPass.setText(Guateroad.ArbolUsuario.PassP(Guateroad.id));
        lblTel.setText(Guateroad.ArbolUsuario.TelefonoP(Guateroad.id));
        lblUser.setText(Guateroad.ArbolUsuario.UsuarioP(Guateroad.id));
    }//GEN-LAST:event_bttGuardarActionPerformed

    private void bttCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCerrarActionPerformed
        Guateroad.ArbolUsuario.BorrarPersona(Guateroad.id);
        Login lg = new Login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_bttCerrarActionPerformed

    private void OpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionesActionPerformed
        
    }//GEN-LAST:event_OpcionesActionPerformed

    private void bttRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRutaActionPerformed
        String LugUs, selectLug, NameConduct, LugConduct; 
        double LatUs, LongUs, LatLug, LongLug, LatConduct, LongConduct, precio;
        int idViaje, idConductor, idFact;
        LugUs = Guateroad.LocUsuario.NombreLugar(Guateroad.id);
        LatUs = Guateroad.HashT.LatLugar(LugUs);
        LongUs = Guateroad.HashT.LongLugar(LugUs);
        selectLug = Opciones.getSelectedItem().toString();
        System.out.println("Lugar seleccionado "+selectLug);
        LatLug = Guateroad.HashT.LatLugar(selectLug);
        LongLug = Guateroad.HashT.LongLugar(selectLug);
        System.out.println("Punto inicial "+ LatUs +  ", " + LongUs);
        System.out.println("Punto final "+ LatLug +  ", " + LongLug);
        
        precio = Guateroad.grafos.Dijkstra(LugUs, selectLug);
        idConductor = Guateroad.fn.QueConductor(LatUs, LongUs);
        NameConduct = Guateroad.ArbolConductor.NombreP(idConductor);
        JOptionPane.showMessageDialog(null, "Conductor designado "+ NameConduct + "\n Precio del viaje Q"+precio, "Viaje", JOptionPane.INFORMATION_MESSAGE);
        
        LugConduct = Guateroad.LocConductor.NombreLugar(Guateroad.id);
        LatConduct = Guateroad.HashT.LatLugar(LugConduct);
        LongConduct = Guateroad.HashT.LongLugar(LugConduct);
        
        String Fecha = "", FormatoFecha;
        Date fechita = new Date();
        FormatoFecha = "dd-MMM-yyyy";
        SimpleDateFormat format = new SimpleDateFormat(FormatoFecha);
        Fecha = format.format(fechita);
        //Fecha = fechita.getDay() + "/" +fechita.getMonth() + "/" + fechita.getYear();
        
        idViaje = Guateroad.ArbolViajes.InsertarViaje(LugUs, selectLug, Fecha);
        Guateroad.bViajes.Insertar(idViaje);
        idFact = Guateroad.ArbolFacturas.InsertarFact(Guateroad.id, idConductor, idViaje, Fecha, precio);
        Guateroad.bFacturas.Insertar(idFact);
        
        Guateroad.MapaGoogle.VerMapa(LatUs, LatLug, LongUs, LongLug, LatConduct, LongConduct);
        
        Guateroad.LocConductor.CambiarDispo(idConductor, true);
    }//GEN-LAST:event_bttRutaActionPerformed

    private void bttInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttInicioActionPerformed
        Login lg = new Login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_bttInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Opciones;
    private javax.swing.JButton bttCerrar;
    private javax.swing.JButton bttGuardar;
    private javax.swing.JButton bttInicio;
    private javax.swing.JButton bttModificar;
    private javax.swing.JButton bttRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
